Cito/Controllers/AboutController.cs
namespace Cito.Controllers
{
    using System.Web.Mvc;

    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return this.View("Index");
        }
    }
}

Cito/Controllers/OfferController.cs
using System;
using System.ComponentModel;
using System.Linq;
using WebGrease.Css.Extensions;

namespace Cito.Controllers
{
    using System.Web.Mvc;
    using Dtos;
    using Models;
    using Services;

    public class OfferController : Controller
    {
        private readonly IOfferService offerService;

        public OfferController(IOfferService offerService)
        {
            this.offerService = offerService;
        }

        [HttpGet]
        public ActionResult List(DisplayListQueryParameters query)
        {
            var viewmodel = this.offerService.GetActiveBuyOffers(query);
            return this.View("List", viewmodel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult NewBuy()
        {
            var model = new NewBuyOfferDto();
            return View("NewBuy", model);
        }


        [HttpPost]
        [Authorize]
        public ActionResult NewBuy(NewBuyOfferDto model)
        {
            if (ModelState.IsValid)
            {
                var result = this.offerService.AddNewBuy(model);
                return this.RedirectToAction("Details", new { id = result.Data });
            }

            return View("NewBuy", model);
        }

        public ActionResult Details(long id)
        {
            var viewmodel = this.offerService.GetBuyOfferDetailsViewModel(id);
            return this.View("Details", viewmodel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NewSell(long id)
        {
            var model = new NewSellOfferDto(id);
            return this.View("NewSell", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult NewSell(NewSellOfferDto model)
        {
            if (ModelState.IsValid)
            {
                var result = this.offerService.AddNewSell(model);
                return this.RedirectToAction("Details", new { id = model.BuyOfferId });
            }

            return View("NewSell", model);
        }
    }
}

Cito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Punkt sprzedaży</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            @Html.ActionLink("Punkt sprzedaży", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Start", "Index", "Home")</li>
                <li>@Html.ActionLink("List ofert", "List", "Offer")</li>
                <li>@Html.ActionLink("Dodaj ofertę kupna", "NewBuy", "Offer")</li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    @Html.ActionLink("Pomoc", "Index", "About", null, new { @class = "btn btn-sm btn-info" })
                </li>
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <nav class="navbar navbar-fixed-bottom">
            <div class="container text-center">
                <p>&copy; @DateTime.Now.Year - Punkt sprzedaży - wersja(20160108-0.1)</p>
            </div>
        </nav>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>