Cito/Controllers/OfferController.cs
using System;
using System.ComponentModel;
using System.Linq;
using WebGrease.Css.Extensions;

namespace Cito.Controllers
{
    using System.Web.Mvc;
    using Dtos;
    using Models;
    using Services;

    public class OfferController : Controller
    {
        private readonly IOfferService offerService;

        public OfferController(IOfferService offerService)
        {
            this.offerService = offerService;
        }

        [HttpGet]
        public ActionResult List(DisplayListQueryParameters query)
        {
            var viewmodel = this.offerService.GetActiveBuyOffers(query);
            return this.View("List", viewmodel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult NewBuy()
        {
            var model = new NewBuyOfferDto();
            return View("NewBuy", model);
        }


        [HttpPost]
        [Authorize]
        public ActionResult NewBuy(NewBuyOfferDto model)
        {
            if (ModelState.IsValid)
            {
                var result = this.offerService.AddNewBuy(model);
                return this.RedirectToAction("Details", new { id = result.Data });
            }

            return View("NewBuy", model);
        }

        public ActionResult Details(long id)
        {
            var viewmodel = this.offerService.GetBuyOfferDetailsViewModel(id);
            return this.View("Details", viewmodel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NewSell(long id)
        {
            var model = new NewSellOfferDto(id);
            return this.View("NewSell", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult NewSell(NewSellOfferDto model)
        {
            if (ModelState.IsValid)
            {
                var result = this.offerService.AddNewSell(model);
                return this.RedirectToAction("Details", new { id = model.BuyOfferId });
            }

            return View("NewSell", model);
        }
    }
}

Cito/Controllers/UserController.cs
using System;

namespace Cito.Controllers
{
    using System.Web.Mvc;
    using Services;

    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public ActionResult Index()
        {
            return this.View("Index");
        }

        public ActionResult Buying()
        {
            var viewmodel = this.userService.GetBuyOffers();
            return this.View("Buying", viewmodel);
        }

        public ActionResult Selling()
        {
            var viewmodel = this.userService.GetSellOffers();
            return this.View("Selling", viewmodel);
        }

        public ActionResult Contact(string id)
        {
            var viewmodel = this.userService.GetContactDetailsForUser(id);
            return this.View("Contact", viewmodel);
        }
    }
}

Cito/Views/Offer/Details.cshtml
@using Microsoft.AspNet.Identity
@model Cito.ViewModels.BuyOfferDetailsViewModel

@{
    ViewBag.Title = "Punkt sprzedaży - oferta kupna";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <hgroup>
        <h1 class="text-center">Oferta kupna</h1>
        <h3 class="text-center text-info">@Model.Title</h3>
    </hgroup>
</div>

<article>
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 clearfix">
            <div>
                @Html.LabelFor(m => m.BuyerName)
                @Html.DisplayFor(m => m.BuyerName)
            </div>

            <div>
                @Html.LabelFor(m => m.Description)
                @Html.DisplayFor(m => m.Description)
            </div>

            <div>
                @Html.LabelFor(m => m.DeliverToCity)
                @Html.DisplayFor(m => m.DeliverToCity)
            </div>
            <div class="row text-center">
                @if (Model.CanPostSellOffers())
                {
                    @Html.ActionLink("Dodaj nową ofertę sprzedaży", "NewSell", "Offer", new { id = Model.Id }, new { @class = "btn btn-primary" })
                }
            </div>
            <div>
                @if (!Model.SellOffers.Any())
                {
                    <p class="text-center text-warning">Ta oferta nie ma jeszcze ofert sprzedaży, bądź pierwszy na liście ofert!</p>
                }
                else
                {
                    <p class="text-center">Zgłoszone oferty sprzedaży:</p>
                    if (!Model.IsCurrentUserIsBuyer())
                    {
                        <p class="text-center text-info">Ceny oraz kontakt jest widoczny tylko dla właściciela aukcji</p>
                    }
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Opis</th>
                                <th>Sposób dostawy</th>
                                <th>Sprzedawca</th>
                                @if (Model.IsCurrentUserIsBuyer())
                                {
                                    <th class="text-right">Cena</th>
                                    <th class="text-right">Opcje</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var sellOffer in Model.SellOffers.OrderByDescending(s => s.Created))
                            {
                                <tr>
                                    <td class="col-lg-4">@sellOffer.Description</td>
                                    <td class="col-lg-4">@sellOffer.DeliveryMethod</td>
                                    <td class="col-lg-2">@sellOffer.Owner.UserName</td>
                                    @if (Model.IsCurrentUserIsBuyer())
                                    {
                                        <td class="text-right col-lg-1">@sellOffer.Price</td>
                                        <td class="text-right col-lg-1">
                                            <p>@Html.ActionLink("kontakt", "Contact", "User", new { id = sellOffer.OwnerId }, new { @class = "btn btn-default btn-sm" })</p>
                                            <p>@Html.ActionLink("akceptuj", "Index", "Home", null, new { @class = "btn btn-default btn-sm" })</p>
                                        </td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
</article>

Cito/Views/Offer/List.cshtml
@model Cito.ViewModels.OfferListViewModel

@{
    ViewBag.Title = "Punkt sprzedaży - lista ofert kupna";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hgroup>
    <h1 class="text-center">Oferty kupna</h1>
</hgroup>

<div class="row">
    <section class="offers col-lg-10 col-lg-offset-1">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>nazwa</th>
                    <th>miasto</th>
                    <th>ważne do</th>
                    <th>opcje</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>nazwa</th>
                    <th>miasto</th>
                    <th>ważne do</th>
                    <th>opcje</th>
                </tr>
            </tfoot>
            <tbody class="table-hover">
                @foreach (var item in Model.BuyOfferList)
            {
                    <tr>
                        <td class="col-lg-6">@item.Title</td>
                        <td class="col-lg-2">@item.DeliverToCity</td>
                        <td class="col-lg-2">@item.ValidUntil</td>
                        <td class="col-lg-2">@Html.ActionLink("Szczegóły", "Details", "Offer", new { id = item.Id }, null)</td>
                    </tr>
                }
            </tbody>
        </table>
        <nav class="text-center">
            <ul class="pagination pagination-lg">
                <li class="@Model.PrevPageCssClass()">
                    <a href="@Url.Action("List", "Offer", new {page = Math.Max(1, @Model.CurrentPage - 1)})" aria-label="Previous">
                        <span aria-hidden="true">
                            &laquo;
                        </span>
                    </a>
                </li>

                @foreach (var availablePage in Model.NavigationPages())
                {
                    <li class="@availablePage.CssClass">
                        @Html.ActionLink(availablePage.Page.ToString(), "List", "Offer", new { page = availablePage.Page }, null)
                    </li>
                }

                <li class="@Model.NextPageCssClass()">
                    <a href="@Url.Action("List", "Offer",new {page=Math.Min(Model.PagesCount, @Model.CurrentPage+1)})" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </section>
</div>

Cito/Views/Offer/NewBuy.cshtml
@model Cito.Dtos.NewBuyOfferDto

@{
    ViewBag.Title = "Punkt sprzedaży - nowa oferta kupna";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <hgroup class="col-lg-10 col-lg-offset-1">
        <h2 class="text-center">Nowa oferta kupna</h2>
    </hgroup>
</div>

<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        @using (Html.BeginForm("NewBuy", "Offer", FormMethod.Post, new { role = "form" }))
        {
            <div class="form-group text-danger">
                @Html.ValidationSummary()
            </div>
            <div class="form-group">
                <div class="text-danger">@Html.ValidationMessageFor(m => m.Title)</div>
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <div class="text-danger">@Html.ValidationMessageFor(m => m.Description)</div>
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <div class="text-danger">@Html.ValidationMessageFor(m => m.DeliverToCity)</div>
                @Html.LabelFor(m => m.DeliverToCity)
                @Html.TextBoxFor(m => m.DeliverToCity, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary pull-right">Dodaj ofertę kupna</button>
        }
    </div>
</div>

Cito/Views/Offer/NewSell.cshtml
@model Cito.Dtos.NewSellOfferDto

@{
    ViewBag.Title = "Punkt sprzedaży - lista oferta sprzedaży";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <hgroup>
        <h2 class="text-center">Nowa oferta sprzedaży</h2>
    </hgroup>
</div>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        @using (Html.BeginForm("NewSell", "Offer", FormMethod.Post, new { role = "form" }))
        {
            <div class="form-group">
                @Html.ValidationSummary()
            </div>

            @Html.HiddenFor(m => m.BuyOfferId)
            <div class="form-group">
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Price)<br/>
                <div class="input-group">
                    @Html.TextBoxFor(m => m.Price, new {@class = "form-control text-right"})
                    <span class="input-group-addon">pln (brutto)</span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.DeliveryMethod)
                @Html.TextAreaFor(m => m.DeliveryMethod, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary pull-right">Dodaj ofertę sprzedaży</button>
        }
    </div>
</div>